"""
Dictum Polyglot C/C++ Binding Generator — v1.1.0

Generates FFI binding code for C and C++ polyglot modules.

Three safety levels:
  SAFE    — All pointer arguments are NULL-checked; strings are bounds-checked;
             complex types go through generated JSON serialisation wrappers.
             Suitable for inter-process / cross-team boundaries.

  UNSAFE  — Raw C ABI, no generated checks, no overhead.
             Caller owns all memory; passing NULL is allowed.
             Required for kernel code, hot paths, embedded targets.

  CHECKED — Unsafe C ABI layout but with runtime assertions injected:
             assert(ptr != NULL), DICTUM_BOUNDS_CHECK(idx, len).
             Debug builds get full checks; release builds strip them via NDEBUG.
             Best of both worlds for development.

Outputs:
  polyglot.h            — Shared C header (structs + forward decls)
  polyglot_safe.h       — Safe wrappers (NULL-checked, serialised complex types)
  polyglot_unsafe.h     — Raw ABI declarations (zero overhead)
  polyglot_checked.h    — ABI + NDEBUG-strippable assertions
  <module>_bindings.c   — Generated C glue (serialisation, NULL wrappers)
  <module>_bindings.cpp — Generated C++17 glue (std::optional, std::string)
"""

from __future__ import annotations
from typing import List, Dict, Optional, Tuple
import textwrap

from ..polyglot_ast import (
    PolyglotInterface, ExportedSymbol, ExportedShape,
    BuildDirective, SafetyLevel,
)


# ---------------------------------------------------------------------------
# Type mapping — Dictum types → C ABI types
# ---------------------------------------------------------------------------

# Safe boundary types (boxed / ref-counted where possible)
_SAFE_TYPE_MAP: Dict[str, str] = {
    'whole number':     'int32_t',
    'count':            'size_t',
    'fractional number':'double',
    'decimal number':   'double',
    'decimal':          'double',
    'truth value':      'int32_t',    # C has no bool across ABI boundaries reliably
    'bool':             'int32_t',
    'byte':             'uint8_t',
    'text':             'const char*',
    'handle to bytes':  'void*',
    'nothing':          'void',
    'u8':  'uint8_t',  'u16': 'uint16_t', 'u32': 'uint32_t',
    'i32': 'int32_t',  'i64': 'int64_t',  'u64': 'uint64_t',
}

# Unsafe / raw pointer types — same as safe but no const on strings
_UNSAFE_TYPE_MAP: Dict[str, str] = {
    **_SAFE_TYPE_MAP,
    'text': 'char*',      # mutable pointer — caller's responsibility
}

# Calling convention attributes
_CALLING_CONV: Dict[str, str] = {
    'cdecl':    '',
    'stdcall':  '__attribute__((stdcall)) ' if True else '__stdcall ',
    'fastcall': '__attribute__((fastcall)) ',
}


def _c_type(dictum_type: str, safety: str, type_map: Optional[Dict] = None) -> str:
    """Map a Dictum type string to a C ABI type string."""
    tm = type_map or (_SAFE_TYPE_MAP if safety != SafetyLevel.UNSAFE else _UNSAFE_TYPE_MAP)
    t = dictum_type.strip()
    if t in tm:
        return tm[t]
    # Pointer types: `raw handle to X`
    for prefix in ('raw handle to ', 'unique handle to ', 'shared handle to ', 'weak handle to '):
        if t.startswith(prefix):
            inner = t[len(prefix):]
            return f"{_c_type(inner, safety, tm)}*"
    # Fallback — use as-is (user-defined struct)
    return t.replace(' ', '_')


def _is_complex(dictum_type: str) -> bool:
    """Returns True if the type needs serialisation across language boundaries."""
    primitives = set(_SAFE_TYPE_MAP.keys())
    t = dictum_type.strip()
    for prefix in ('raw handle to', 'unique handle to', 'shared handle to', 'weak handle to'):
        if t.startswith(prefix):
            return False
    return t not in primitives


# ---------------------------------------------------------------------------
# Header preamble helpers
# ---------------------------------------------------------------------------

_PREAMBLE = """\
/*
 * GENERATED BY DICTUM POLYGLOT LINKER v1.1.0
 * DO NOT EDIT — regenerate with: dictumc --polyglot-link
 *
 * Module  : {module}
 * Backend : {backend}
 * Safety  : {safety}
 * Interop : {interop}
 */
#pragma once
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
"""

_SAFE_PREAMBLE_EXTRA = """\
/* ── Safe boundary helpers ───────────────────────────────── */
#ifndef DICTUM_SAFE_CALL
#  define DICTUM_SAFE_CALL(fn, ...) (fn)(__VA_ARGS__)
#endif
#ifndef DICTUM_NULL_CHECK
#  define DICTUM_NULL_CHECK(ptr) \\
    do { if ((ptr) == NULL) { return 0; } } while(0)
#endif
#ifndef DICTUM_NULL_CHECK_VOID
#  define DICTUM_NULL_CHECK_VOID(ptr) \\
    do { if ((ptr) == NULL) { return; } } while(0)
#endif
"""

_UNSAFE_PREAMBLE_EXTRA = """\
/* ── Unsafe boundary — NO automatic checks ──────────────── */
/* Caller is responsible for:                                 */
/*   - NULL pointer checks                                    */
/*   - Buffer length bounds                                   */
/*   - Memory lifetime / ownership transfer                   */
#ifndef DICTUM_UNSAFE
#  define DICTUM_UNSAFE
#endif
"""

_CHECKED_PREAMBLE_EXTRA = """\
/* ── Checked boundary — assertions stripped by NDEBUG ───── */
#include <assert.h>
#ifndef DICTUM_CHECK_PTR
#  ifndef NDEBUG
#    define DICTUM_CHECK_PTR(p)    assert((p) != NULL)
#    define DICTUM_CHECK_BOUNDS(i,n) assert((size_t)(i) < (size_t)(n))
#    define DICTUM_CHECK_STR(s)    assert((s) != NULL && (s)[0] != '\\0')
#  else
#    define DICTUM_CHECK_PTR(p)    ((void)0)
#    define DICTUM_CHECK_BOUNDS(i,n) ((void)0)
#    define DICTUM_CHECK_STR(s)    ((void)0)
#  endif
#endif
"""


# ---------------------------------------------------------------------------
# Main generator class
# ---------------------------------------------------------------------------

class CppBindingGenerator:
    """
    Generates all C/C++ binding files for a polyglot interface.

    Call generate() to get a dict of filename → content.
    """

    def __init__(self, iface: PolyglotInterface, all_interfaces: Dict[str, PolyglotInterface]):
        self.iface = iface
        self.all_interfaces = all_interfaces

    def generate(self) -> Dict[str, str]:
        files: Dict[str, str] = {}
        m = self.iface.module_name

        # Always generate the shared struct header
        files[f"{m}_polyglot.h"] = self._gen_shared_header()

        # Safety-specific headers
        if self.iface.safety == SafetyLevel.SAFE or self.iface.backend in ('c', 'cpp'):
            files[f"{m}_safe.h"] = self._gen_safe_header()
            files[f"{m}_safe.c"] = self._gen_safe_impl()

        if self.iface.safety == SafetyLevel.UNSAFE or self.iface.backend in ('c', 'cpp'):
            files[f"{m}_unsafe.h"] = self._gen_unsafe_header()
            # Unsafe has no impl — it's direct symbol calls

        if self.iface.safety == SafetyLevel.CHECKED or self.iface.backend in ('c', 'cpp'):
            files[f"{m}_checked.h"] = self._gen_checked_header()
            files[f"{m}_checked.c"] = self._gen_checked_impl()

        # C++ bindings (RAII wrappers)
        if self.iface.backend == 'cpp' or self.iface.backend in ('c', 'cpp'):
            files[f"{m}_cxx.hpp"] = self._gen_cpp_header()
            files[f"{m}_cxx.cpp"] = self._gen_cpp_impl()

        # JSON serialisation wrappers for complex types
        if any(s.serializable for s in self.iface.shapes):
            files[f"{m}_serial.h"]  = self._gen_serial_header()
            files[f"{m}_serial.c"]  = self._gen_serial_impl()

        return files

    # ------------------------------------------------------------------
    # Shared struct header  (module_polyglot.h)
    # ------------------------------------------------------------------
    def _gen_shared_header(self) -> str:
        m = self.iface.module_name
        lines = [
            _PREAMBLE.format(
                module=m, backend=self.iface.backend,
                safety=self.iface.safety, interop=self.iface.interop,
            ),
            f'#ifndef DICTUM_{m.upper()}_POLYGLOT_H',
            f'#define DICTUM_{m.upper()}_POLYGLOT_H',
            '',
            '#ifdef __cplusplus',
            'extern "C" {',
            '#endif',
            '',
            '/* ── Exported Struct Layouts ─────────────────────── */',
        ]
        for shape in self.iface.shapes:
            lines.extend(self._emit_struct(shape))

        lines += [
            '',
            '/* ── Forward Declarations ────────────────────────── */',
        ]
        for sym in self.iface.exports:
            lines.append(self._emit_fwd_decl(sym, SafetyLevel.SAFE) + ';')

        lines += [
            '',
            '#ifdef __cplusplus',
            '}  /* extern "C" */',
            '#endif',
            f'#endif  /* DICTUM_{m.upper()}_POLYGLOT_H */',
        ]
        return '\n'.join(lines)

    def _emit_struct(self, shape: ExportedShape) -> List[str]:
        lines = []
        if shape.packed:
            lines.append(f'#pragma pack(push, 1)')
        lines.append(f'typedef struct {{')
        for fname, ftype in shape.fields:
            ct = _c_type(ftype, SafetyLevel.SAFE)
            lines.append(f'    {ct} {fname};')
        lines.append(f'}} {shape.name};')
        if shape.packed:
            lines.append(f'#pragma pack(pop)')
        lines.append('')
        return lines

    def _emit_fwd_decl(self, sym: ExportedSymbol, safety: str) -> str:
        ret = _c_type(sym.ret_type, safety)
        params = ', '.join(
            f'{_c_type(pt, safety)} {pn}' for pn, pt in sym.params
        ) or 'void'
        conv = _CALLING_CONV.get(sym.calling_conv, '')
        prefix = f'DICTUM_EXPORT ' if True else ''
        return f'{ret} {conv}{sym.c_name}({params})'

    # ------------------------------------------------------------------
    # SAFE header  (module_safe.h)
    # ------------------------------------------------------------------
    def _gen_safe_header(self) -> str:
        m = self.iface.module_name
        lines = [
            _PREAMBLE.format(
                module=m, backend=self.iface.backend,
                safety='safe', interop=self.iface.interop,
            ),
            _SAFE_PREAMBLE_EXTRA,
            f'#include "{m}_polyglot.h"',
            f'#ifndef DICTUM_{m.upper()}_SAFE_H',
            f'#define DICTUM_{m.upper()}_SAFE_H',
            '',
            '#ifdef __cplusplus',
            'extern "C" {',
            '#endif',
            '',
            '/* ── Safe Wrappers ───────────────────────────────── */',
            '/* All pointer args are NULL-checked before dispatch.  */',
            '/* Returns 0 / NULL on null-arg violations.            */',
            '',
        ]
        for sym in self.iface.exports:
            lines.extend(self._emit_safe_wrapper_decl(sym))

        lines += [
            '',
            '#ifdef __cplusplus',
            '}  /* extern "C" */',
            '#endif',
            f'#endif  /* DICTUM_{m.upper()}_SAFE_H */',
        ]
        return '\n'.join(lines)

    def _emit_safe_wrapper_decl(self, sym: ExportedSymbol) -> List[str]:
        """Emit a safe wrapper declaration with doc comment."""
        ret = _c_type(sym.ret_type, SafetyLevel.SAFE)
        params_str = ', '.join(
            f'{_c_type(pt, SafetyLevel.SAFE)} {pn}' for pn, pt in sym.params
        ) or 'void'
        lines = [
            f'/**',
            f' * [SAFE] {sym.name}',
        ]
        for pn, pt in sym.params:
            if _c_type(pt, SafetyLevel.SAFE).endswith('*'):
                lines.append(f' * @param {pn}  Must NOT be NULL (checked at boundary).')
        if sym.thread_safe:
            lines.append(' * @threadsafe  This function is thread-safe.')
        lines += [
            f' */',
            f'{ret} dictum_safe_{sym.c_name}({params_str});',
            '',
        ]
        return lines

    def _gen_safe_impl(self) -> str:
        """Generate the C implementation file for safe wrappers."""
        m = self.iface.module_name
        lines = [
            f'/* Safe wrapper implementation for {m} */',
            f'#include "{m}_safe.h"',
            f'#include <string.h>',
            f'#include <stdlib.h>',
            '',
        ]
        for sym in self.iface.exports:
            lines.extend(self._emit_safe_impl(sym))
        return '\n'.join(lines)

    def _emit_safe_impl(self, sym: ExportedSymbol) -> List[str]:
        ret = _c_type(sym.ret_type, SafetyLevel.SAFE)
        is_void = sym.ret_type in ('nothing', 'void', '')
        params_str = ', '.join(
            f'{_c_type(pt, SafetyLevel.SAFE)} {pn}' for pn, pt in sym.params
        ) or 'void'
        call_args = ', '.join(pn for pn, _ in sym.params)

        lines = [f'{ret} dictum_safe_{sym.c_name}({params_str}) {{']

        # NULL checks for all pointer params
        for pn, pt in sym.params:
            ct = _c_type(pt, SafetyLevel.SAFE)
            if ct.endswith('*'):
                if is_void:
                    lines.append(f'    DICTUM_NULL_CHECK_VOID({pn});')
                else:
                    null_ret = '0' if ret in ('int32_t','size_t','double','uint8_t') else 'NULL'
                    lines.append(f'    if ({pn} == NULL) {{ return {null_ret}; }}')

        # String length safety for text params
        for pn, pt in sym.params:
            if pt.strip() in ('text',):
                lines.append(f'    if (strlen({pn}) > 65535) {{ return {"0" if not is_void else ""}; }}')

        # Dispatch to the raw symbol
        if is_void:
            lines.append(f'    {sym.c_name}({call_args});')
        else:
            lines.append(f'    return {sym.c_name}({call_args});')

        lines += ['}', '']
        return lines

    # ------------------------------------------------------------------
    # UNSAFE header  (module_unsafe.h)
    # ------------------------------------------------------------------
    def _gen_unsafe_header(self) -> str:
        m = self.iface.module_name
        lines = [
            _PREAMBLE.format(
                module=m, backend=self.iface.backend,
                safety='unsafe', interop=self.iface.interop,
            ),
            _UNSAFE_PREAMBLE_EXTRA,
            f'#include "{m}_polyglot.h"',
            f'#ifndef DICTUM_{m.upper()}_UNSAFE_H',
            f'#define DICTUM_{m.upper()}_UNSAFE_H',
            '',
            '#ifdef __cplusplus',
            'extern "C" {',
            '#endif',
            '',
            '/* ── Raw ABI Declarations ────────────────────────── */',
            '/* Zero overhead. No NULL checks. Caller owns memory.  */',
            '',
        ]
        for sym in self.iface.exports:
            ret = _c_type(sym.ret_type, SafetyLevel.UNSAFE)
            params_str = ', '.join(
                f'{_c_type(pt, SafetyLevel.UNSAFE)} {pn}' for pn, pt in sym.params
            ) or 'void'
            conv = _CALLING_CONV.get(sym.calling_conv, '')
            lines.append(f'/* unsafe */ {ret} {conv}{sym.c_name}({params_str});')
            # Also provide a macro alias: DICTUM_UNSAFE_<name> = raw call
            lines.append(
                f'#define DICTUM_UNSAFE_{sym.c_name.upper()}({", ".join(pn for pn,_ in sym.params)}) '
                f'{sym.c_name}({", ".join(pn for pn,_ in sym.params)})'
            )
            lines.append('')

        lines += [
            '#ifdef __cplusplus',
            '}  /* extern "C" */',
            '#endif',
            f'#endif  /* DICTUM_{m.upper()}_UNSAFE_H */',
        ]
        return '\n'.join(lines)

    # ------------------------------------------------------------------
    # CHECKED header  (module_checked.h)
    # ------------------------------------------------------------------
    def _gen_checked_header(self) -> str:
        m = self.iface.module_name
        lines = [
            _PREAMBLE.format(
                module=m, backend=self.iface.backend,
                safety='checked', interop=self.iface.interop,
            ),
            _CHECKED_PREAMBLE_EXTRA,
            f'#include "{m}_polyglot.h"',
            f'#ifndef DICTUM_{m.upper()}_CHECKED_H',
            f'#define DICTUM_{m.upper()}_CHECKED_H',
            '',
            '#ifdef __cplusplus',
            'extern "C" {',
            '#endif',
            '',
            '/* ── Checked Wrappers ────────────────────────────── */',
            '/* Asserts in debug builds. Zero overhead with NDEBUG.  */',
            '',
        ]
        for sym in self.iface.exports:
            lines.extend(self._emit_checked_wrapper_decl(sym))

        lines += [
            '#ifdef __cplusplus',
            '}  /* extern "C" */',
            '#endif',
            f'#endif  /* DICTUM_{m.upper()}_CHECKED_H */',
        ]
        return '\n'.join(lines)

    def _emit_checked_wrapper_decl(self, sym: ExportedSymbol) -> List[str]:
        ret = _c_type(sym.ret_type, SafetyLevel.CHECKED)
        params_str = ', '.join(
            f'{_c_type(pt, SafetyLevel.CHECKED)} {pn}' for pn, pt in sym.params
        ) or 'void'
        lines = [
            f'/* [CHECKED] {sym.name} — asserts stripped by NDEBUG */',
            f'{ret} dictum_checked_{sym.c_name}({params_str});',
            '',
        ]
        return lines

    def _gen_checked_impl(self) -> str:
        m = self.iface.module_name
        lines = [
            f'/* Checked wrapper implementation for {m} */',
            f'#include "{m}_checked.h"',
            '',
        ]
        for sym in self.iface.exports:
            lines.extend(self._emit_checked_impl(sym))
        return '\n'.join(lines)

    def _emit_checked_impl(self, sym: ExportedSymbol) -> List[str]:
        ret = _c_type(sym.ret_type, SafetyLevel.CHECKED)
        is_void = sym.ret_type in ('nothing', 'void', '')
        params_str = ', '.join(
            f'{_c_type(pt, SafetyLevel.CHECKED)} {pn}' for pn, pt in sym.params
        ) or 'void'
        call_args = ', '.join(pn for pn, _ in sym.params)

        lines = [f'{ret} dictum_checked_{sym.c_name}({params_str}) {{']

        # Checked pointer assertions (stripped by NDEBUG)
        for pn, pt in sym.params:
            ct = _c_type(pt, SafetyLevel.CHECKED)
            if ct.endswith('*'):
                lines.append(f'    DICTUM_CHECK_PTR({pn});')
            if pt.strip() == 'text':
                lines.append(f'    DICTUM_CHECK_STR({pn});')

        if is_void:
            lines.append(f'    {sym.c_name}({call_args});')
        else:
            lines.append(f'    return {sym.c_name}({call_args});')

        lines += ['}', '']
        return lines

    # ------------------------------------------------------------------
    # C++ header  (module_cxx.hpp)
    # ------------------------------------------------------------------
    def _gen_cpp_header(self) -> str:
        m = self.iface.module_name
        cap = m.capitalize()
        lines = [
            _PREAMBLE.format(
                module=m, backend=self.iface.backend,
                safety=self.iface.safety, interop=self.iface.interop,
            ),
            '#include <memory>',
            '#include <string>',
            '#include <optional>',
            '#include <stdexcept>',
            '#include <functional>',
            f'#include "{m}_polyglot.h"',
            f'#ifndef DICTUM_{m.upper()}_CXX_HPP',
            f'#define DICTUM_{m.upper()}_CXX_HPP',
            '',
            f'namespace dictum::{m} {{',
            '',
            '/* ── C++ RAII / std::optional wrappers ──────────── */',
            '/* These wrap raw C symbols with:                      */',
            '/*   - std::optional return types (no sentinel values) */',
            '/*   - std::string for text args (auto-managed)        */',
            '/*   - nullptr → std::nullopt propagation              */',
            '/*   - std::runtime_error on fatal failures            */',
            '',
        ]

        # Struct wrappers
        for shape in self.iface.shapes:
            lines.extend(self._emit_cpp_struct_wrapper(shape))

        # Function wrappers
        for sym in self.iface.exports:
            lines.extend(self._emit_cpp_func_wrapper(sym))

        lines += [
            f'}}  /* namespace dictum::{m} */',
            f'#endif  /* DICTUM_{m.upper()}_CXX_HPP */',
        ]
        return '\n'.join(lines)

    def _emit_cpp_struct_wrapper(self, shape: ExportedShape) -> List[str]:
        lines = [
            f'/* Wrapped: {shape.name} */',
            f'struct {shape.name}Wrapper {{',
            f'    {shape.name} raw;',
            f'',
            f'    {shape.name}Wrapper() : raw{{}} {{}}',
            f'    explicit {shape.name}Wrapper({shape.name} r) : raw(r) {{}}',
            '',
        ]
        # Typed accessors
        for fname, ftype in shape.fields:
            ct = _c_type(ftype, SafetyLevel.SAFE)
            cpp_type = self._dictum_to_cpp(ftype)
            lines.append(f'    {cpp_type} get_{fname}() const {{ return raw.{fname}; }}')
            lines.append(f'    void set_{fname}({cpp_type} v) {{ raw.{fname} = v; }}')
        lines += ['};', '']
        return lines

    def _emit_cpp_func_wrapper(self, sym: ExportedSymbol) -> List[str]:
        is_void = sym.ret_type in ('nothing', 'void', '')
        cpp_ret = self._dictum_to_cpp(sym.ret_type)

        # Convert params: text → std::string_view, pointers stay as-is
        cpp_params = []
        c_call_args = []
        for pn, pt in sym.params:
            cpp_t = self._dictum_to_cpp(pt)
            cpp_params.append(f'{cpp_t} {pn}')
            # Convert std::string → .c_str() at call site
            if pt.strip() == 'text':
                c_call_args.append(f'{pn}.c_str()')
            else:
                c_call_args.append(pn)

        params_str = ', '.join(cpp_params) or ''
        call_str = ', '.join(c_call_args)

        lines = [
            f'/**',
            f' * [C++ wrapper] {sym.name}',
            f' * Returns std::optional<{cpp_ret}> — nullopt on failure.' if not is_void else f' * Void return.',
            f' */',
        ]

        if is_void:
            lines += [
                f'inline void {sym.name}({params_str}) {{',
                f'    {sym.c_name}({call_str});',
                f'}}',
            ]
        else:
            lines += [
                f'inline std::optional<{cpp_ret}> {sym.name}({params_str}) {{',
                f'    auto result = {sym.c_name}({call_str});',
            ]
            # Pointer return: nullopt on NULL
            if _c_type(sym.ret_type, SafetyLevel.SAFE).endswith('*'):
                lines.append(f'    if (result == nullptr) return std::nullopt;')
            lines += [
                f'    return result;',
                f'}}',
            ]
        lines.append('')
        return lines

    def _dictum_to_cpp(self, dictum_type: str) -> str:
        """Map Dictum type to idiomatic C++ type."""
        t = dictum_type.strip()
        mapping = {
            'whole number':     'int32_t',
            'count':            'std::size_t',
            'fractional number':'double',
            'decimal number':   'double',
            'decimal':          'double',
            'truth value':      'bool',
            'bool':             'bool',
            'byte':             'uint8_t',
            'text':             'std::string',
            'handle to bytes':  'void*',
            'nothing':          'void',
            'u8':  'uint8_t',  'u16': 'uint16_t', 'u32': 'uint32_t',
            'i32': 'int32_t',  'i64': 'int64_t',  'u64': 'uint64_t',
        }
        if t in mapping:
            return mapping[t]
        for prefix in ('unique handle to ', 'shared handle to ', 'raw handle to '):
            if t.startswith(prefix):
                inner = self._dictum_to_cpp(t[len(prefix):])
                if prefix.startswith('unique'):
                    return f'std::unique_ptr<{inner}>'
                if prefix.startswith('shared'):
                    return f'std::shared_ptr<{inner}>'
                return f'{inner}*'
        return t.replace(' ', '_')

    def _gen_cpp_impl(self) -> str:
        m = self.iface.module_name
        return '\n'.join([
            f'/* C++ binding implementation for {m} */',
            f'/* All inline — no separate translation unit needed.  */',
            f'#include "{m}_cxx.hpp"',
        ])

    # ------------------------------------------------------------------
    # JSON serialisation  (module_serial.h / .c)
    # ------------------------------------------------------------------
    def _gen_serial_header(self) -> str:
        m = self.iface.module_name
        lines = [
            f'/* JSON serialisation for {m} polyglot types */',
            '#pragma once',
            '#include <stddef.h>',
            f'#include "{m}_polyglot.h"',
            '',
            '#ifdef __cplusplus',
            'extern "C" {',
            '#endif',
            '',
        ]
        for shape in self.iface.shapes:
            if not shape.serializable:
                continue
            n = shape.name
            lines += [
                f'/* Serialise {n} to JSON string. Caller must free() the result. */',
                f'char* {n}_to_json(const {n}* obj);',
                f'',
                f'/* Deserialise {n} from JSON string. Returns 1 on success, 0 on parse error. */',
                f'int {n}_from_json(const char* json, {n}* out);',
                '',
            ]
        lines += [
            '#ifdef __cplusplus',
            '}',
            '#endif',
        ]
        return '\n'.join(lines)

    def _gen_serial_impl(self) -> str:
        m = self.iface.module_name
        lines = [
            f'/* JSON serialisation implementation for {m} */',
            f'/* Uses a minimal hand-written JSON encoder/decoder.     */',
            f'/* Replace with cJSON / jansson for production use.      */',
            f'#include "{m}_serial.h"',
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <string.h>',
            '',
        ]
        for shape in self.iface.shapes:
            if not shape.serializable:
                continue
            lines.extend(self._emit_serial_impl(shape))
        return '\n'.join(lines)

    def _emit_serial_impl(self, shape: ExportedShape) -> List[str]:
        n = shape.name
        lines = []

        # to_json
        lines += [
            f'char* {n}_to_json(const {n}* obj) {{',
            f'    if (obj == NULL) return NULL;',
            f'    /* estimate buffer: 64 bytes per field */',
            f'    size_t cap = {max(256, len(shape.fields) * 64)};',
            f'    char* buf = (char*)malloc(cap);',
            f'    if (buf == NULL) return NULL;',
            f'    int pos = 0;',
            f'    pos += snprintf(buf + pos, cap - pos, "{{");',
        ]
        for i, (fname, ftype) in enumerate(shape.fields):
            sep = '' if i == len(shape.fields) - 1 else ','
            ct = _c_type(ftype, SafetyLevel.SAFE)
            if ftype.strip() == 'text':
                lines.append(f'    pos += snprintf(buf + pos, cap - pos, "\\"{fname}\\":\\"%s\\"{sep}", obj->{fname} ? obj->{fname} : "");')
            elif ct in ('double', 'float'):
                lines.append(f'    pos += snprintf(buf + pos, cap - pos, "\\"{fname}\\":%f{sep}", obj->{fname});')
            elif ct in ('int32_t', 'int64_t', 'size_t', 'uint32_t', 'uint64_t', 'uint8_t', 'uint16_t'):
                lines.append(f'    pos += snprintf(buf + pos, cap - pos, "\\"{fname}\\":%ld{sep}", (long)obj->{fname});')
            else:
                lines.append(f'    pos += snprintf(buf + pos, cap - pos, "\\"{fname}\\":null{sep}");')
        lines += [
            f'    pos += snprintf(buf + pos, cap - pos, "}}");',
            f'    return buf;',
            f'}}',
            '',
        ]

        # from_json — field-by-field parser.
        # Text fields: inline string extractor that heap-allocates and copies the
        #   JSON string value (handles \" escapes, null-terminates).
        # Numeric fields: sscanf with correct format specifier.
        # Bool fields: strcmp against "true"/"false".
        lines += [
            f'int {n}_from_json(const char* json, {n}* out) {{',
            f'    if (json == NULL || out == NULL) return 0;',
            f'    memset(out, 0, sizeof({n}));',
        ]
        for fname, ftype in shape.fields:
            ct = _c_type(ftype, SafetyLevel.SAFE)
            pattern_key = f'\\"{fname}\\":'
            key_len = len(pattern_key)
            if ftype.strip() == 'text':
                # Find "fname": then skip whitespace, expect opening quote,
                # copy bytes until unescaped closing quote, strdup into out->field.
                lines += [
                    f'    {{',
                    f'        const char* _k = strstr(json, "{pattern_key}");',
                    f'        if (_k) {{',
                    f'            _k += {key_len};',
                    f'            while (*_k == \' \' || *_k == \'\\t\') _k++;',
                    f'            if (*_k == \'"\') {{',
                    f'                const char* _s = ++_k;',
                    f'                size_t _n = 0;',
                    f'                while (*_k) {{',
                    f'                    if (*_k == \'"\' && (_k == _s || *(_k-1) != \'\\\\\')) break;',
                    f'                    _k++; _n++;',
                    f'                }}',
                    f'                char* _buf = (char*)malloc(_n + 1);',
                    f'                if (_buf) {{ memcpy(_buf, _s, _n); _buf[_n] = \'\\0\'; }}',
                    f'                out->{fname} = _buf;',
                    f'            }}',
                    f'        }}',
                    f'    }}',
                ]
            elif ct in ('bool',):
                lines += [
                    f'    {{ const char* _k = strstr(json, "{pattern_key}");',
                    f'       if (_k) {{ _k += {key_len};',
                    f'                 while (*_k == \' \') _k++;',
                    f'                 out->{fname} = (strncmp(_k, "true", 4) == 0); }} }}',
                ]
            elif ct in ('double', 'float'):
                lines.append(
                    f'    {{ const char* _k = strstr(json, "{pattern_key}");'
                    f' if (_k) sscanf(_k + {key_len}, "%lf", (double*)&out->{fname}); }}'
                )
            else:
                lines.append(
                    f'    {{ const char* _k = strstr(json, "{pattern_key}");'
                    f' if (_k) sscanf(_k + {key_len}, "%ld", (long*)&out->{fname}); }}'
                )
        lines += [
            f'    return 1;',
            f'}}',
            '',
        ]
        return lines
