"""
Dictum Polyglot Linker — v1.1.0

The main linker. Takes:
  - A list of PolyglotInterface objects (one per polyglot module)
  - The desired output directory

Produces:
  - All binding headers and C/C++ glue files (via CppBindingGenerator)
  - A unified polyglot_registry.h  (one header to rule them all)
  - Makefile with correct -l flags for each module
  - CMakeLists.txt for CMake users
  - polyglot_demo.c  — a working demo that calls every exported function

Supports:
  - Safe, Unsafe, Checked C ABI  (for C and C++ modules)
  - C++ RAII wrappers             (dictum::<module>::<fn>)
  - JSON serialisation glue       (@serializable shapes)
  - gRPC stub generation (skeleton — requires protoc)
  - HTTP/REST stub generation     (skeleton — requires curl)
"""

from __future__ import annotations
import os
from typing import Dict, List, Tuple, Optional

from ..polyglot_ast import (
    PolyglotInterface, ExportedSymbol, ExportedShape,
    BuildDirective, SafetyLevel,
)
from .binding_generator import CppBindingGenerator, _c_type


class PolyglotLinker:
    """
    Links all polyglot module interfaces into binding glue.

    Usage:
        linker = PolyglotLinker(interfaces, output_dir="build/polyglot")
        files = linker.link()
        linker.write(files)      # writes to disk
    """

    def __init__(self,
                 interfaces: Dict[str, PolyglotInterface],
                 output_dir: str = "build/polyglot",
                 project_name: str = "dictum_project"):
        self.interfaces = interfaces
        self.output_dir = output_dir
        self.project_name = project_name

    # ------------------------------------------------------------------
    def link(self) -> Dict[str, str]:
        """Run the full link pass. Returns dict of relative_path → file_content."""
        files: Dict[str, str] = {}

        # Generate per-module bindings
        for name, iface in self.interfaces.items():
            gen = CppBindingGenerator(iface, self.interfaces)
            module_files = gen.generate()
            for fname, content in module_files.items():
                files[fname] = content

        # Generate unified registry header
        files["polyglot_registry.h"] = self._gen_registry()

        # Build system files
        files["Makefile"]        = self._gen_makefile()
        files["CMakeLists.txt"]  = self._gen_cmake()
        files["polyglot_demo.c"] = self._gen_demo_c()
        files["polyglot_demo.cpp"] = self._gen_demo_cpp()

        # Interop stubs for non-C backends
        for name, iface in self.interfaces.items():
            if iface.interop == 'grpc':
                files[f"{name}.proto"] = self._gen_proto(iface)
            elif iface.interop == 'http':
                files[f"{name}_openapi.yaml"] = self._gen_openapi(iface)

        return files

    def write(self, files: Dict[str, str]) -> None:
        """Write all generated files to output_dir."""
        os.makedirs(self.output_dir, exist_ok=True)
        for fname, content in files.items():
            path = os.path.join(self.output_dir, fname)
            os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(content)

    # ------------------------------------------------------------------
    # Unified registry header
    # ------------------------------------------------------------------
    def _gen_registry(self) -> str:
        lines = [
            '/*',
            ' * polyglot_registry.h — GENERATED BY DICTUM POLYGLOT LINKER v1.1.0',
            ' * Single header that includes ALL module bindings.',
            ' * Include this one header to get the full polyglot API.',
            ' */',
            '#pragma once',
            '',
            '/* Module inventory */',
        ]
        for name, iface in self.interfaces.items():
            lines += [
                f'/* Module: {name}  backend={iface.backend}  safety={iface.safety}  interop={iface.interop} */',
                f'#include "{name}_polyglot.h"',
                f'#include "{name}_safe.h"',
                f'#include "{name}_unsafe.h"',
                f'#include "{name}_checked.h"',
            ]
            if iface.backend == 'cpp':
                lines.append(f'#include "{name}_cxx.hpp"')
            if any(s.serializable for s in iface.shapes):
                lines.append(f'#include "{name}_serial.h"')
            lines.append('')

        lines += [
            '/* ── Convenience macros ──────────────────────────── */',
            '/* DICTUM_CALL_SAFE(module, fn, ...)   → dictum_safe_{fn}(...)    */',
            '/* DICTUM_CALL_UNSAFE(module, fn, ...) → {fn}(...)                */',
            '/* DICTUM_CALL_CHECKED(module, fn, ...) → dictum_checked_{fn}()   */',
            '',
            '#define DICTUM_CALL_SAFE(mod, fn, ...)     dictum_safe_##fn(__VA_ARGS__)',
            '#define DICTUM_CALL_UNSAFE(mod, fn, ...)   fn(__VA_ARGS__)',
            '#define DICTUM_CALL_CHECKED(mod, fn, ...)  dictum_checked_##fn(__VA_ARGS__)',
        ]
        return '\n'.join(lines)

    # ------------------------------------------------------------------
    # Makefile
    # ------------------------------------------------------------------
    def _gen_makefile(self) -> str:
        # Collect build directives
        link_libs: List[str] = []
        cflags_extra: List[str] = []
        ldflags_extra: List[str] = []
        include_paths: List[str] = []

        for iface in self.interfaces.values():
            for d in iface.build_directives:
                if d.kind == 'link' and d.value:
                    link_libs.append(f'-l{d.value.lstrip("-l")}')
                elif d.kind == 'cflags' and d.value:
                    cflags_extra.append(d.value)
                elif d.kind == 'ldflags' and d.value:
                    ldflags_extra.append(d.value)
                elif d.kind == 'include_path' and d.value:
                    include_paths.append(f'-I{d.value}')

        # Deduplicate
        link_libs   = list(dict.fromkeys(link_libs))
        cflags_extra = list(dict.fromkeys(cflags_extra))
        ldflags_extra = list(dict.fromkeys(ldflags_extra))
        include_paths = list(dict.fromkeys(include_paths))

        # Always include -lm
        if '-lm' not in link_libs:
            link_libs.insert(0, '-lm')

        all_c_srcs = []
        for name in self.interfaces:
            all_c_srcs += [f"{name}_safe.c", f"{name}_checked.c"]
            if any(s.serializable for s in self.interfaces[name].shapes):
                all_c_srcs.append(f"{name}_serial.c")

        srcs_str = ' '.join(all_c_srcs)
        libs_str  = ' '.join(link_libs + ldflags_extra)
        cf_str    = ' '.join(['-Wall', '-Wextra', '-std=c11'] + cflags_extra + include_paths)
        cf_cpp    = ' '.join(['-Wall', '-Wextra', '-std=c++17'] + cflags_extra + include_paths)

        lines = [
            f'# Dictum Polyglot Linker — Generated Makefile',
            f'# Project: {self.project_name}',
            f'CC      = gcc',
            f'CXX     = g++',
            f'CFLAGS  = {cf_str}',
            f'CXXFLAGS= {cf_cpp}',
            f'LDFLAGS = {libs_str}',
            f'SRCS_C  = {srcs_str}',
            f'OBJS_C  = $(SRCS_C:.c=.o)',
            f'',
            f'all: libpolyglot.so libpolyglot.a polyglot_demo',
            f'',
            f'libpolyglot.so: $(OBJS_C)',
            f'\t$(CC) -shared -fPIC -o $@ $^ $(LDFLAGS)',
            f'',
            f'libpolyglot.a: $(OBJS_C)',
            f'\tar rcs $@ $^',
            f'',
            f'polyglot_demo: polyglot_demo.c libpolyglot.a',
            f'\t$(CC) $(CFLAGS) -o $@ $< -L. -lpolyglot $(LDFLAGS)',
            f'',
            f'polyglot_demo_cpp: polyglot_demo.cpp libpolyglot.a',
            f'\t$(CXX) $(CXXFLAGS) -o $@ $< -L. -lpolyglot $(LDFLAGS)',
            f'',
            f'%.o: %.c',
            f'\t$(CC) $(CFLAGS) -fPIC -c -o $@ $<',
            f'',
            f'clean:',
            f'\trm -f *.o *.so *.a polyglot_demo polyglot_demo_cpp',
            f'',
            f'.PHONY: all clean',
        ]
        return '\n'.join(lines)

    # ------------------------------------------------------------------
    # CMakeLists.txt
    # ------------------------------------------------------------------
    def _gen_cmake(self) -> str:
        link_libs = ['m']
        for iface in self.interfaces.values():
            for d in iface.build_directives:
                if d.kind == 'link' and d.value:
                    link_libs.append(d.value.lstrip('-l'))

        srcs = []
        for name in self.interfaces:
            srcs += [f"{name}_safe.c", f"{name}_checked.c"]

        lines = [
            f'cmake_minimum_required(VERSION 3.16)',
            f'project({self.project_name} C CXX)',
            f'',
            f'set(CMAKE_C_STANDARD 11)',
            f'set(CMAKE_CXX_STANDARD 17)',
            f'',
            f'# Polyglot binding sources',
            f'set(POLYGLOT_SRCS',
        ]
        for s in srcs:
            lines.append(f'    {s}')
        lines += [
            f')',
            f'',
            f'add_library(polyglot STATIC ${{POLYGLOT_SRCS}})',
            f'target_include_directories(polyglot PUBLIC ${{CMAKE_CURRENT_SOURCE_DIR}})',
            f'target_link_libraries(polyglot {" ".join(link_libs)})',
            f'',
            f'# Demo executables',
            f'add_executable(polyglot_demo polyglot_demo.c)',
            f'target_link_libraries(polyglot_demo polyglot)',
            f'',
            f'add_executable(polyglot_demo_cpp polyglot_demo.cpp)',
            f'target_link_libraries(polyglot_demo_cpp polyglot)',
            f'',
            f'# Install',
            f'install(TARGETS polyglot ARCHIVE DESTINATION lib)',
            f'install(FILES polyglot_registry.h DESTINATION include/dictum)',
        ]
        return '\n'.join(lines)

    # ------------------------------------------------------------------
    # Demo C file
    # ------------------------------------------------------------------
    def _gen_demo_c(self) -> str:
        lines = [
            '/*',
            ' * polyglot_demo.c — Generated demo for all polyglot modules.',
            ' * Demonstrates safe, unsafe, and checked call patterns.',
            ' */',
            '#include "polyglot_registry.h"',
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '',
            'int main(void) {',
            '    printf("Dictum Polyglot Demo\\n");',
            '',
        ]
        for name, iface in self.interfaces.items():
            lines += [
                f'    /* ── Module: {name} (backend={iface.backend}, safety={iface.safety}) ── */',
            ]
            for sym in iface.exports:
                if sym.safety == SafetyLevel.UNSAFE:
                    lines.append(f'    /* unsafe call: {sym.c_name} — skipping in demo for safety */')
                    continue
                # Build dummy args
                call_args = []
                for pn, pt in sym.params:
                    ct = _c_type(pt, SafetyLevel.SAFE)
                    if ct.endswith('*'):
                        call_args.append('NULL')
                    elif ct in ('double', 'float'):
                        call_args.append('0.0')
                    elif pt.strip() == 'text':
                        call_args.append('"demo"')
                    else:
                        call_args.append('0')
                args_str = ', '.join(call_args)
                lines.append(f'    printf("  [safe] {sym.c_name}(...)\\n");')
                if sym.ret_type in ('nothing', 'void', ''):
                    lines.append(f'    dictum_safe_{sym.c_name}({args_str});')
                else:
                    lines.append(f'    (void)dictum_safe_{sym.c_name}({args_str});')
            lines.append('')

        lines += [
            '    printf("Demo complete.\\n");',
            '    return 0;',
            '}',
        ]
        return '\n'.join(lines)

    def _gen_demo_cpp(self) -> str:
        lines = [
            '/*',
            ' * polyglot_demo.cpp — C++ RAII wrapper demo.',
            ' */',
            '#include "polyglot_registry.h"',
            '#include <iostream>',
            '',
            'int main() {',
            '    std::cout << "Dictum Polyglot C++ Demo" << std::endl;',
            '',
        ]
        for name, iface in self.interfaces.items():
            if iface.backend not in ('c', 'cpp'):
                continue
            for sym in iface.exports:
                call_args = []
                for pn, pt in sym.params:
                    if pt.strip() == 'text':
                        call_args.append('"demo"')
                    else:
                        call_args.append('0')
                ns = f'dictum::{name}'
                args_str = ', '.join(call_args)
                lines.append(f'    std::cout << "  [cxx] {name}::{sym.name}" << std::endl;')
                if sym.ret_type in ('nothing', 'void', ''):
                    lines.append(f'    {ns}::{sym.name}({args_str});')
                else:
                    lines.append(f'    auto r_{sym.c_name} = {ns}::{sym.name}({args_str});')
                    lines.append(f'    if (!r_{sym.c_name}.has_value()) std::cout << "    → nullopt" << std::endl;')
            lines.append('')

        lines += [
            '    std::cout << "C++ Demo complete." << std::endl;',
            '    return 0;',
            '}',
        ]
        return '\n'.join(lines)

    # ------------------------------------------------------------------
    # gRPC .proto stub
    # ------------------------------------------------------------------
    def _gen_proto(self, iface: PolyglotInterface) -> str:
        m = iface.module_name
        lines = [
            f'// Generated Protobuf schema for {m}',
            f'// Run: protoc --c_out=. {m}.proto',
            f'syntax = "proto3";',
            f'package dictum.{m};',
            '',
            f'service {m.capitalize()}Service {{',
        ]
        for sym in iface.exports:
            req = f'{sym.name.capitalize()}Request'
            res = f'{sym.name.capitalize()}Response'
            lines.append(f'  rpc {sym.name.capitalize()} ({req}) returns ({res});')
        lines += ['', '}', '']

        for sym in iface.exports:
            req = f'{sym.name.capitalize()}Request'
            res = f'{sym.name.capitalize()}Response'
            lines += [f'message {req} {{']
            for i, (pn, pt) in enumerate(sym.params, 1):
                proto_t = self._dictum_to_proto(pt)
                lines.append(f'  {proto_t} {pn} = {i};')
            lines += ['}', '']

            lines += [f'message {res} {{']
            if sym.ret_type not in ('nothing', 'void', ''):
                lines.append(f'  {self._dictum_to_proto(sym.ret_type)} result = 1;')
            lines += ['}', '']

        return '\n'.join(lines)

    def _dictum_to_proto(self, t: str) -> str:
        mapping = {
            'whole number': 'int32', 'count': 'uint64',
            'fractional number': 'double', 'decimal number': 'double',
            'decimal': 'double', 'truth value': 'bool', 'bool': 'bool',
            'byte': 'uint32', 'text': 'string', 'handle to bytes': 'bytes',
            'i32': 'int32', 'i64': 'int64', 'u32': 'uint32', 'u64': 'uint64',
        }
        return mapping.get(t.strip(), 'bytes')

    # ------------------------------------------------------------------
    # OpenAPI YAML stub
    # ------------------------------------------------------------------
    def _gen_openapi(self, iface: PolyglotInterface) -> str:
        m = iface.module_name
        lines = [
            f'openapi: "3.0.3"',
            f'info:',
            f'  title: "{m} Polyglot HTTP API"',
            f'  version: "1.0.0"',
            f'  description: "Generated by Dictum Polyglot Linker v1.1.0"',
            f'paths:',
        ]
        for sym in iface.exports:
            lines += [
                f'  /{sym.name}:',
                f'    post:',
                f'      summary: "{sym.name}"',
                f'      requestBody:',
                f'        required: true',
                f'        content:',
                f'          application/json:',
                f'            schema:',
                f'              type: object',
                f'              properties:',
            ]
            for pn, pt in sym.params:
                oa_type = self._dictum_to_openapi(pt)
                lines.append(f'                {pn}:')
                lines.append(f'                  type: "{oa_type}"')
            lines += [
                f'      responses:',
                f'        "200":',
                f'          description: Success',
            ]
        return '\n'.join(lines)

    def _dictum_to_openapi(self, t: str) -> str:
        mapping = {
            'whole number': 'integer', 'count': 'integer',
            'fractional number': 'number', 'decimal number': 'number',
            'truth value': 'boolean', 'bool': 'boolean',
            'text': 'string', 'byte': 'integer',
        }
        return mapping.get(t.strip(), 'string')
